[project]
name = "certificates-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "google-adk[a2a]>=1.17.0",
    "python-dotenv>=1.1.1",
]
